/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package asiento;

import java.awt.Color;

/**
 *
 * @author macbook
 */
public class SelectorColores extends javax.swing.JPanel {

    /**
     * Creates new form SelectorColores
     */
    public SelectorColores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTFColorLibre = new javax.swing.JTextField();
        jTFColorOcupado = new javax.swing.JTextField();
        jTFColorSeleccionado = new javax.swing.JTextField();
        jTFColorEncima = new javax.swing.JTextField();
        jLColorLibre = new javax.swing.JLabel();
        jLColorOcupado = new javax.swing.JLabel();
        jLColorSeleccionado = new javax.swing.JLabel();
        jLColorEncima = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jTFColorEncima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFColorEncimaActionPerformed(evt);
            }
        });

        jLColorLibre.setText("Color Libre:");

        jLColorOcupado.setText("Color ocupado:");

        jLColorSeleccionado.setText("Color Seleccionado:");

        jLColorEncima.setText("Color Encima:");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Indica los colores en hexadecimal. Ej.: #FFFF10 ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLColorLibre)
                            .addComponent(jLColorOcupado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTFColorOcupado, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                            .addComponent(jTFColorLibre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLColorSeleccionado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLColorEncima)
                                .addGap(41, 41, 41)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTFColorEncima, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addComponent(jTFColorSeleccionado))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFColorLibre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLColorLibre)
                    .addComponent(jTFColorEncima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLColorEncima))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFColorOcupado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLColorOcupado)
                    .addComponent(jTFColorSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLColorSeleccionado))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTFColorEncimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFColorEncimaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFColorEncimaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLColorEncima;
    private javax.swing.JLabel jLColorLibre;
    private javax.swing.JLabel jLColorOcupado;
    private javax.swing.JLabel jLColorSeleccionado;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTFColorEncima;
    private javax.swing.JTextField jTFColorLibre;
    private javax.swing.JTextField jTFColorOcupado;
    private javax.swing.JTextField jTFColorSeleccionado;
    // End of variables declaration//GEN-END:variables

    public ColoresAsiento getPropiedadSeleccionada(){
        if(jTFColorLibre.getText().isBlank()||jTFColorEncima.getText().isBlank()||jTFColorOcupado.getText().isBlank()||jTFColorSeleccionado.getText().isBlank()){
            return null;
        }else {
            Color colorLibre = Color.decode(jTFColorLibre.getText());
            Color colorEncima = Color.decode(jTFColorEncima.getText());
            Color colorOcupado = Color.decode(jTFColorOcupado.getText());
            Color colorSeleccionado = Color.decode(jTFColorSeleccionado.getText());
            return new ColoresAsiento(colorLibre,colorSeleccionado,colorOcupado,colorEncima);
        }
}

}
