/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package asientos_grada.gui;

import java.awt.Frame;

/**
 *
 * @author macbook
 */
public class VentanaOcupacionGrada extends javax.swing.JDialog {

    /**
     * Creates new form VentanaOcupacionGrada
     */
    public VentanaOcupacionGrada(Frame parent, boolean modal, int ocupados, int libres) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        String asientosOcupados=""+ocupados;
        String asientosLibres=""+libres;
        jLNumeroAsientoOcupados.setText(asientosOcupados);
        jLNumeroAsientosLibres.setText(asientosLibres);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLAsientosLibres = new javax.swing.JLabel();
        jLAsientoOcupados = new javax.swing.JLabel();
        jLNumeroAsientosLibres = new javax.swing.JLabel();
        jLNumeroAsientoOcupados = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ocupación Polideportivo");
        setLocation(new java.awt.Point(50, 50));
        setResizable(false);

        jLAsientosLibres.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLAsientosLibres.setForeground(new java.awt.Color(0, 102, 204));
        jLAsientosLibres.setText("Asientos Libres:");
        jLAsientosLibres.setToolTipText("");

        jLAsientoOcupados.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLAsientoOcupados.setForeground(new java.awt.Color(255, 0, 0));
        jLAsientoOcupados.setText("Asientos Ocupados:");

        jLNumeroAsientosLibres.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLNumeroAsientosLibres.setForeground(new java.awt.Color(0, 102, 204));
        jLNumeroAsientosLibres.setText("000");
        jLNumeroAsientosLibres.setToolTipText("");

        jLNumeroAsientoOcupados.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLNumeroAsientoOcupados.setForeground(new java.awt.Color(255, 0, 0));
        jLNumeroAsientoOcupados.setText("000");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLAsientosLibres)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLNumeroAsientosLibres))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLAsientoOcupados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLNumeroAsientoOcupados)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLAsientoOcupados, jLNumeroAsientoOcupados, jLNumeroAsientosLibres});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLAsientosLibres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLNumeroAsientosLibres))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLAsientoOcupados)
                    .addComponent(jLNumeroAsientoOcupados))
                .addGap(120, 120, 120))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLAsientoOcupados, jLNumeroAsientoOcupados, jLNumeroAsientosLibres});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLAsientoOcupados;
    private javax.swing.JLabel jLAsientosLibres;
    private javax.swing.JLabel jLNumeroAsientoOcupados;
    private javax.swing.JLabel jLNumeroAsientosLibres;
    // End of variables declaration//GEN-END:variables

   
}
