/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package asientos_grada.gui;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author macbook
 */
public class VentanaReservar extends javax.swing.JDialog {
    
    private VentanaPrincipal ventanaPrincipal;
    /**
     * Creates new form VentanaReservar
     * @param parent
     * @param modal
     * @param asientosReservados
     * @param ventanaPrincipal
     */
    public VentanaReservar(java.awt.Frame parent, boolean modal, String asientosReservados, VentanaPrincipal ventanaPrincipal) {
        super(parent, modal);
        this.ventanaPrincipal=ventanaPrincipal;
        initComponents();
        setLocationRelativeTo(parent);
        jTAListaAsientosReservados.setEditable(false);
        jTAListaAsientosReservados.setText(asientosReservados);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLNombre = new javax.swing.JLabel();
        jLApellidos = new javax.swing.JLabel();
        jTFNombre = new javax.swing.JTextField();
        jTFApellidos = new javax.swing.JTextField();
        jLAsientosSeleccionados = new javax.swing.JLabel();
        jPListaAsientosSeleccionados = new javax.swing.JPanel();
        jSPListaAsientosSeleccionados = new javax.swing.JScrollPane();
        jTAListaAsientosReservados = new javax.swing.JTextArea();
        jBReservar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jLMensajeIntroducirDatos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reservar");

        jLNombre.setText("Nombre:");
        jLNombre.setToolTipText("");

        jLApellidos.setText("Apellidos:");

        jTFNombre.setText(" ");

        jTFApellidos.setText(" ");

        jLAsientosSeleccionados.setText("Asientos Seleccionados:");

        jPListaAsientosSeleccionados.setBackground(new java.awt.Color(231, 231, 231));
        jPListaAsientosSeleccionados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jSPListaAsientosSeleccionados.setFocusable(false);
        jSPListaAsientosSeleccionados.setHorizontalScrollBar(null);

        jTAListaAsientosReservados.setColumns(20);
        jTAListaAsientosReservados.setForeground(new java.awt.Color(153, 153, 153));
        jTAListaAsientosReservados.setRows(5);
        jSPListaAsientosSeleccionados.setViewportView(jTAListaAsientosReservados);

        javax.swing.GroupLayout jPListaAsientosSeleccionadosLayout = new javax.swing.GroupLayout(jPListaAsientosSeleccionados);
        jPListaAsientosSeleccionados.setLayout(jPListaAsientosSeleccionadosLayout);
        jPListaAsientosSeleccionadosLayout.setHorizontalGroup(
            jPListaAsientosSeleccionadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPListaAsientosSeleccionadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSPListaAsientosSeleccionados, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPListaAsientosSeleccionadosLayout.setVerticalGroup(
            jPListaAsientosSeleccionadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPListaAsientosSeleccionadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSPListaAsientosSeleccionados, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBReservar.setText("Reservar");
        jBReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBReservarActionPerformed(evt);
            }
        });

        jBCancelar.setText("Cancelar");
        jBCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBCancelarMouseClicked(evt);
            }
        });

        jLMensajeIntroducirDatos.setForeground(new java.awt.Color(255, 51, 51));
        jLMensajeIntroducirDatos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLMensajeIntroducirDatos.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPListaAsientosSeleccionados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLAsientosSeleccionados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBCancelar))
                    .addComponent(jBReservar)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLNombre)
                            .addComponent(jLApellidos))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFApellidos)
                            .addComponent(jTFNombre)))
                    .addComponent(jLMensajeIntroducirDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLNombre)
                    .addComponent(jTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLApellidos)
                    .addComponent(jTFApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLAsientosSeleccionados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPListaAsientosSeleccionados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLMensajeIntroducirDatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBReservar)
                    .addComponent(jBCancelar))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBCancelarMouseClicked
        ventanaPrincipal.desmarcarBotonesSeleccionados();
        dispose();
    }//GEN-LAST:event_jBCancelarMouseClicked

    private void jBReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBReservarActionPerformed
        if (validarFormulario()){
            String nombre=jTFNombre.getText();
            String apellidos=jTFApellidos.getText();
            Date date=new Date();
            ventanaPrincipal.reservarAsientos(nombre, apellidos, date);
            dispose();
        }else {
            jLMensajeIntroducirDatos.setText("Debes introducir el nombre y los apellidos.");
        }
    }//GEN-LAST:event_jBReservarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBReservar;
    private javax.swing.JLabel jLApellidos;
    private javax.swing.JLabel jLAsientosSeleccionados;
    private javax.swing.JLabel jLMensajeIntroducirDatos;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JPanel jPListaAsientosSeleccionados;
    private javax.swing.JScrollPane jSPListaAsientosSeleccionados;
    private javax.swing.JTextArea jTAListaAsientosReservados;
    private javax.swing.JTextField jTFApellidos;
    private javax.swing.JTextField jTFNombre;
    // End of variables declaration//GEN-END:variables

    private boolean validarFormulario() {
        boolean check = true;
        String nombre = jTFNombre.getText().trim();
        String apellidos = jTFApellidos.getText().trim();
        if (nombre.isEmpty() || apellidos.isEmpty()) {
            check = false;
        }
        return check;
    }
}
